name: unit_tests
on:
  push:
    branches:
      - main
      - fbw2_test
  pull_request:
    branches:
      - main
jobs:
  test-jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "rwth-i6/i6_models"
          path: ""
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'
      - run: |
          pip install -r requirements.txt
      - name: Test Ops
        run: |
          python -m unittest -v test
